apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "${MASTER_IP_ADDRESS}"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  podSubnet: "172.16.0.0/16"
apiServer:
  certSANs:
  - "${MASTER_IP_ADDRESS}"
  extraArgs:
    oidc-issuer-url: https://192.168.205.9:8443/auth/realms/master
    oidc-username-claim: preferred_username
    oidc-client-id: local-kubernetes
    oidc-groups-claim: groups
